### ISSUE TITLE
Update the readme to remove multiple instances of Gilbert Skill Score (GSS)

### ISSUE THREAD

**Issue by shiv3679** [Debasish-Mahapatra/nwpeval#8]
- Gilbert Skill Score (GS) <--- Instance @ 1 
  - Symmetric Extreme Dependency Score (SEDS)
  - Frequency Bias (FB)
  - Gilbert Skill Score (GSS) <--- Instance @ 2

**Comment by Debasish-Mahapatra** [comment]
Updated readme, to remove multiple instances of GSS
